import { NextResponse } from "next/server";
import nodemailer from "nodemailer";

export async function POST(request: Request) {
  try {
    const { name, email, company, subject, message } = await request.json();

    // Basic Validation
    if (!name || !email || !subject || !message) {
      return NextResponse.json(
        { error: "Missing required fields (Name, Email, Subject, Message)." },
        { status: 400 }
      );
    }

    const emailTo = "sylvie.servicez@gmail.com";

    // Check if SMTP environment variables are set
    const smtpUser = process.env.EMAIL_USER;
    const smtpPass = process.env.EMAIL_PASS;
    const smtpHost = process.env.SMTP_HOST || "smtp.gmail.com";
    const smtpPort = parseInt(process.env.SMTP_PORT || "465");

    const mailOptions = {
      from: smtpUser ? `"${name} (${company || "No Company"})" <${smtpUser}>` : `"${name}" <${email}>`,
      replyTo: email,
      to: emailTo,
      subject: `[Sylvie Automation Lead] ${subject}`,
      text: `
Name: ${name}
Email: ${email}
Company: ${company || "Not Provided"}
Topic: ${subject}

Message / Details:
${message}
      `,
      html: `
        <div style="font-family: sans-serif; max-width: 600px; margin: 0 auto; padding: 20px; border: 1px solid #e2e8f0; border-radius: 8px; background-color: #ffffff; color: #1a202c;">
          <h2 style="color: #2d5bff; border-bottom: 2px solid #e2e8f0; padding-bottom: 10px; margin-top: 0;">New Sylvie Automation Inquiry</h2>
          <table style="width: 100%; border-collapse: collapse; margin-top: 15px;">
            <tr>
              <td style="padding: 8px 0; font-weight: bold; width: 120px;">Name:</td>
              <td style="padding: 8px 0;">${name}</td>
            </tr>
            <tr>
              <td style="padding: 8px 0; font-weight: bold;">Email:</td>
              <td style="padding: 8px 0;"><a href="mailto:${email}" style="color: #2d5bff;">${email}</a></td>
            </tr>
            <tr>
              <td style="padding: 8px 0; font-weight: bold;">Company:</td>
              <td style="padding: 8px 0;">${company || "Not Provided"}</td>
            </tr>
            <tr>
              <td style="padding: 8px 0; font-weight: bold;">Topic:</td>
              <td style="padding: 8px 0; font-weight: bold; color: #571bc1;">${subject}</td>
            </tr>
          </table>
          <div style="margin-top: 20px; padding: 15px; background-color: #f7fafc; border-left: 4px solid #2d5bff; border-radius: 4px;">
            <h4 style="margin-top: 0; margin-bottom: 8px; color: #4a5568;">Message / Details:</h4>
            <p style="margin: 0; white-space: pre-wrap; line-height: 1.6; color: #2d3748;">${message}</p>
          </div>
          <p style="font-size: 11px; color: #a0aec0; text-align: center; margin-top: 30px; border-top: 1px solid #e2e8f0; padding-top: 15px;">
            This email was automatically generated by the Sylvie AI website contact portal.
          </p>
        </div>
      `,
    };

    if (smtpUser && smtpPass) {
      // Create transport
      const transporter = nodemailer.createTransport({
        host: smtpHost,
        port: smtpPort,
        secure: smtpPort === 465, // true for 465, false for other ports
        auth: {
          user: smtpUser,
          pass: smtpPass,
        },
      });

      // Send mail
      await transporter.sendMail(mailOptions);
      console.log(`[Sylvie API] Contact form email successfully sent to ${emailTo}`);
    } else {
      // Mock Send: Log message in development environment
      console.warn(
        "\n=================== SYLVIE CONTACT FORM SUBMISSION ===================\n" +
        "WARNING: SMTP credentials (EMAIL_USER / EMAIL_PASS) are not set.\n" +
        "Email content has been logged below instead of dispatched:\n\n" +
        `Recipient: ${emailTo}\n` +
        `Sender: ${name} (${email}) | Company: ${company || "None"}\n` +
        `Subject: ${mailOptions.subject}\n` +
        `Text:\n${mailOptions.text.trim()}\n` +
        "=====================================================================\n"
      );
    }

    return NextResponse.json({ success: true, message: "Inquiry processed successfully." });
  } catch (error: any) {
    console.error("[Sylvie API Error] Failed to process contact request:", error);
    return NextResponse.json(
      { error: "Internal server error. Failed to process your request." },
      { status: 500 }
    );
  }
}
